# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Biztags
Biztag.create(:name => "High End")
Biztag.create(:name => "Boutique")

# Boroughs 
Borough.create(:name => "Manhattan")
Borough.create(:name => "The Bronx")
Borough.create(:name => "Brooklyn")
Borough.create(:name => "Staten Island")
Borough.create(:name => "New Jersey")
Borough.create(:name => "Queens")

# Neighborhoods
# Neighborhood.create(:name => "Upper East Side")
# Neighborhood.create(:name => "Williamsburg")

# Designers 
Designer.create(:name => "3.1 Phillip Lim")
Designer.create(:name => "Alexander Wang")
Designer.create(:name => "Alice & Olivia")
Designer.create(:name => "Anthropologie")
Designer.create(:name => "Asos")
Designer.create(:name => "Balenciaga")
Designer.create(:name => "BCBG")
Designer.create(:name => "Bebe")
Designer.create(:name => "Betsey Johnson")
Designer.create(:name => "Burberry")
Designer.create(:name => "Calvin Klein")
Designer.create(:name => "Celine")
Designer.create(:name => "Chanel")
Designer.create(:name => "Chloe")
Designer.create(:name => "Christian Dior")
Designer.create(:name => "Christian Louboutin")
Designer.create(:name => "Coach")
Designer.create(:name => "Cole Haan")
Designer.create(:name => "David Yurman")
Designer.create(:name => "DVF")
Designer.create(:name => "DKNY")
Designer.create(:name => "Dolce & Gabbana")
Designer.create(:name => "Elizabeth & James")
Designer.create(:name => "Express")
Designer.create(:name => "Fendi")
Designer.create(:name => "Free People")
Designer.create(:name => "Furla")
Designer.create(:name => "Gorjana")
Designer.create(:name => "Gucci")
Designer.create(:name => "House of Harlow")
Designer.create(:name => "Hermes")
Designer.create(:name => "J.Brand")
Designer.create(:name => "J.Crew")
Designer.create(:name => "Juicy Couture")
Designer.create(:name => "Kate Spade")
Designer.create(:name => "Kenneth Cole")
Designer.create(:name => "Levi's")
Designer.create(:name => "Louis Vuitton")
Designer.create(:name => "Lucky Brand")
Designer.create(:name => "Lululemon")
Designer.create(:name => "Madewell")
Designer.create(:name => "Marc Jacobs")
Designer.create(:name => "Michael Kors")
Designer.create(:name => "Nasty Gal")
Designer.create(:name => "Nine West")
Designer.create(:name => "Prada")
Designer.create(:name => "Ralph Lauren")
Designer.create(:name => "Rebecca Minkoff")
Designer.create(:name => "Stella & Dot")
Designer.create(:name => "Theory")
Designer.create(:name => "Tiffany & Co.")
Designer.create(:name => "Tory Burch")
Designer.create(:name => "Trina Turk")
Designer.create(:name => "True Religion")
Designer.create(:name => "UGG")
Designer.create(:name => "Urban Outfitters")
Designer.create(:name => "Versace")
Designer.create(:name => "YSL")
Designer.create(:name => "Zara")


