require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NeighborhoodsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Neighborhood. As you add validations to Neighborhood, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NeighborhoodsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all neighborhoods as @neighborhoods" do
      neighborhood = Neighborhood.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:neighborhoods)).to eq([neighborhood])
    end
  end

  describe "GET show" do
    it "assigns the requested neighborhood as @neighborhood" do
      neighborhood = Neighborhood.create! valid_attributes
      get :show, {:id => neighborhood.to_param}, valid_session
      expect(assigns(:neighborhood)).to eq(neighborhood)
    end
  end

  describe "GET new" do
    it "assigns a new neighborhood as @neighborhood" do
      get :new, {}, valid_session
      expect(assigns(:neighborhood)).to be_a_new(Neighborhood)
    end
  end

  describe "GET edit" do
    it "assigns the requested neighborhood as @neighborhood" do
      neighborhood = Neighborhood.create! valid_attributes
      get :edit, {:id => neighborhood.to_param}, valid_session
      expect(assigns(:neighborhood)).to eq(neighborhood)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Neighborhood" do
        expect {
          post :create, {:neighborhood => valid_attributes}, valid_session
        }.to change(Neighborhood, :count).by(1)
      end

      it "assigns a newly created neighborhood as @neighborhood" do
        post :create, {:neighborhood => valid_attributes}, valid_session
        expect(assigns(:neighborhood)).to be_a(Neighborhood)
        expect(assigns(:neighborhood)).to be_persisted
      end

      it "redirects to the created neighborhood" do
        post :create, {:neighborhood => valid_attributes}, valid_session
        expect(response).to redirect_to(Neighborhood.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved neighborhood as @neighborhood" do
        post :create, {:neighborhood => invalid_attributes}, valid_session
        expect(assigns(:neighborhood)).to be_a_new(Neighborhood)
      end

      it "re-renders the 'new' template" do
        post :create, {:neighborhood => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested neighborhood" do
        neighborhood = Neighborhood.create! valid_attributes
        put :update, {:id => neighborhood.to_param, :neighborhood => new_attributes}, valid_session
        neighborhood.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested neighborhood as @neighborhood" do
        neighborhood = Neighborhood.create! valid_attributes
        put :update, {:id => neighborhood.to_param, :neighborhood => valid_attributes}, valid_session
        expect(assigns(:neighborhood)).to eq(neighborhood)
      end

      it "redirects to the neighborhood" do
        neighborhood = Neighborhood.create! valid_attributes
        put :update, {:id => neighborhood.to_param, :neighborhood => valid_attributes}, valid_session
        expect(response).to redirect_to(neighborhood)
      end
    end

    describe "with invalid params" do
      it "assigns the neighborhood as @neighborhood" do
        neighborhood = Neighborhood.create! valid_attributes
        put :update, {:id => neighborhood.to_param, :neighborhood => invalid_attributes}, valid_session
        expect(assigns(:neighborhood)).to eq(neighborhood)
      end

      it "re-renders the 'edit' template" do
        neighborhood = Neighborhood.create! valid_attributes
        put :update, {:id => neighborhood.to_param, :neighborhood => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested neighborhood" do
      neighborhood = Neighborhood.create! valid_attributes
      expect {
        delete :destroy, {:id => neighborhood.to_param}, valid_session
      }.to change(Neighborhood, :count).by(-1)
    end

    it "redirects to the neighborhoods list" do
      neighborhood = Neighborhood.create! valid_attributes
      delete :destroy, {:id => neighborhood.to_param}, valid_session
      expect(response).to redirect_to(neighborhoods_url)
    end
  end

end
